datasource:
  driver_class: org.postgresql.Driver
  url_db: jdbc:postgresql://localhost:5432/car_showroom
  username_db: postgres
  password_db: postgres

hibernate:
  show_sql: true
  ddl_auto: none
  dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  change_log: db.changelog/changelog-master.xml
