spring:
  application:
    name:car-showroom
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car_showroom
    username: postgres
    password: postgres

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: db.changelog/changelog-master.xml

server:
  port: 8090
