spring:
  application:
    name:car-showroom
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car_showroom
    username: postgres
    password: postgres

  jpa:
    generate-ddl: false
    show-sql: true

server:
  port: 8090
